server:
  port: 8181

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

app:
  auth:
    tokenSecret: ${TOKEN_SECRET}
#    tokenExpirationMsec: 864000000 #10 days
#    tokenExpirationMsec: 300000 #5 mins
    tokenExpirationMsec: 86400000 #1 days
  firebase:
    databaseUrl: ${FIREBASE_DATABASE}
    googleCredentials: ${GOOGLE_APPLICATION_CREDENTIALS}
  verificationExpirationMsec: 300000 #5 mins
  eventCancelationValidMaxMsec: 86400000 #24 hours