package com.mitrais.chipper.temankondangan.backendapps.controller;

import java.io.IOException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.mitrais.chipper.temankondangan.backendapps.model.Profile;
import com.mitrais.chipper.temankondangan.backendapps.model.json.ProfileUpdateWrapper;
import com.mitrais.chipper.temankondangan.backendapps.service.ProfileService;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;

@Api(value="Profile Management System", description="Operations regarding profile in TemenKondangan System")
@RestController
@Validated
@RequestMapping("/profile")
public class ProfileController {
	
	@Autowired
	private ProfileService profileService;

	@ApiOperation(value = "Get profile by user id", response = Profile.class)
	@GetMapping("/getByUserId/{userId}")
	@ApiParam(value = "user id generated by db system", required = true)
	public Profile getByUserId(@PathVariable Long userId) {
		
		return profileService.getProfile(userId);
	}

}
