CREATE TABLE public.users (
	user_id int8 PRIMARY KEY,
	email varchar NOT NULL,
	password_hashed varchar,
	created_by varchar NOT NULL,
	created_date timestamp NOT NULL,
	modified_by varchar NOT NULL,
	modified_date timestamp NOT NULL,
    provider varchar NOT NULL,
    provider_id varchar
);

CREATE table public.profile (
	profile_id int8 PRIMARY KEY,
	user_id int8 NOT NULL REFERENCES users(user_id),
	full_name varchar NOT NULL,
	dob date NOT NULL,
	gender varchar(1) NOT NULL,
	photo_profile oid NULL,
	city varchar NULL,
	about_me varchar(200) NULL,
	interest varchar(200) NULL,
	created_by varchar NOT NULL,
    created_date timestamp NOT NULL,
    modified_by varchar NOT NULL,
    modified_date timestamp NOT NULL
);

CREATE TABLE public.config (
	config_id int8 PRIMARY KEY,
	config_key varchar NOT NULL,
	config_value varchar NOT NULL,
	created_by varchar NOT NULL,
	created_date timestamp NOT NULL,
	modified_by varchar NOT NULL,
	modified_date timestamp NOT NULL
);

CREATE TABLE public.event
(
    event_id int8 PRIMARY KEY,
	user_id int8 NOT NULL REFERENCES users(user_id),
    additional_info varchar(300) NOT NULL,
    companion_gender varchar(1) NOT NULL,
    date_and_time timestamp without time zone NOT NULL,
    maximum_age integer NOT NULL,
    minimum_age integer NOT NULL,
    title varchar(50),
	created_by varchar NOT NULL,
	created_date timestamp NOT NULL,
	last_modified_by varchar NOT NULL,
	last_modified_date timestamp NOT NULL
);

CREATE TABLE public.verification_code (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp NULL,
	email varchar(255) NULL,
	code varchar(255) NULL,
	CONSTRAINT temp_password_pkey PRIMARY KEY (id)
);

CREATE TABLE public.applicants (
	id int8 NOT NULL,
	data_state varchar(255) NOT NULL,
	status varchar(255) NOT NULL,
	user_id int8 NULL,
	event_id int8 NULL,
	CONSTRAINT applicants_pkey PRIMARY KEY (id),
	CONSTRAINT fkagqbys02vwt92fq9e00u10ou1 FOREIGN KEY (event_id) REFERENCES event(event_id),
	CONSTRAINT fks48x9ywgx7l6mg1egokmys0gp FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE public.ratings (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	event_id int8 NULL,
	score int4 NULL,
	user_id int8 NULL,
	CONSTRAINT ratings_pkey PRIMARY KEY (id)
);

CREATE TABLE public.notifications (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	title varchar(50) NULL,
	body varchar(255) NULL,
	user_id int8 NULL,
	is_read BOOLEAN NULL,
	CONSTRAINT notifications_pkey PRIMARY KEY (id),
	CONSTRAINT notifications_users_fkey FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE public.revinfo (
	rev int4 NOT NULL,
	revtstmp int8 NULL,
	CONSTRAINT revinfo_pkey PRIMARY KEY (rev)
);

CREATE TABLE public.event_aud (
	event_id int8 NOT NULL,
	rev int4 NOT NULL,
	revtype int2 NULL,
	additional_info varchar(300) NULL,
	additional_info_mod bool NULL,
	cancelled bool NULL,
	cancelled_mod bool NULL,
	city varchar(255) NULL,
	city_mod bool NULL,
	companion_gender varchar(1) NULL,
	companion_gender_mod bool NULL,
	data_state varchar(255) NULL,
	data_state_mod bool NULL,
	finish_date_time timestamp NULL,
	finish_date_time_mod bool NULL,
	maximum_age int4 NULL,
	maximum_age_mod bool NULL,
	minimum_age int4 NULL,
	minimum_age_mod bool NULL,
	start_date_time timestamp NULL,
	start_date_time_mod bool NULL,
	title varchar(50) NULL,
	title_mod bool NULL,
	user_id int8 NULL,
	CONSTRAINT event_aud_pkey PRIMARY KEY (event_id, rev),
	CONSTRAINT fk76r0s14ewob41mu1pe3qdbdke FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

CREATE TABLE public.chatroom (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	event_id int8 NULL,
	data_state VARCHAR NOT NULL DEFAULT 'ACTIVE',
	CONSTRAINT chatroom_pkey PRIMARY KEY (id),
	CONSTRAINT chatroom_event_fkey FOREIGN KEY (event_id) REFERENCES event(event_id)
);

CREATE TABLE public.chatroom_user (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	chatroom_id int8 NULL,
	user_id int8 NULL,
	CONSTRAINT chatroomuser_pkey PRIMARY KEY (id),
	CONSTRAINT chatroomuser_chatroom_fkey FOREIGN KEY (chatroom_id) REFERENCES chatroom(id),
	CONSTRAINT chatroomuser_user_fkey FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE public.chat (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	chatroom_id int8 NULL,
	user_id int8 NULL,
	body varchar(255) NULL,
	CONSTRAINT chat_pkey PRIMARY KEY (id),
	CONSTRAINT chat_chatroom_fkey FOREIGN KEY (chatroom_id) REFERENCES chatroom(id),
	CONSTRAINT chat_user_fkey FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE public.chat_log (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	chat_id int8 NULL,
	user_id int8 NULL,
	received_date timestamp NULL,
	read_date timestamp NULL,
	CONSTRAINT chat_log_pkey PRIMARY KEY (id),	
	CONSTRAINT chat_log_chat_fkey FOREIGN KEY (chat_id) REFERENCES chat(id),
	CONSTRAINT chat_log_user_fkey FOREIGN KEY (user_id) REFERENCES users(user_id)
);