INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Aceh Barat, Aceh','Kab. Aceh Barat, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Aceh Barat Daya, Aceh','Kab. Aceh Barat Daya, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Aceh Besar, Aceh','Kab. Aceh Besar, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Aceh Jaya, Aceh','Kab. Aceh Jaya, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Aceh Selatan, Aceh','Kab. Aceh Selatan, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Aceh Singkil, Aceh','Kab. Aceh Singkil, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Aceh Tamiang, Aceh','Kab. Aceh Tamiang, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Aceh Tengah, Aceh','Kab. Aceh Tengah, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Aceh Tenggara, Aceh','Kab. Aceh Tenggara, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Aceh Timur, Aceh','Kab. Aceh Timur, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Aceh Utara, Aceh','Kab. Aceh Utara, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Agam, Sumatera Barat','Kab. Agam, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Alor, Nusa Tenggara Timur','Kab. Alor, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Ambon, Maluku','Kota Ambon, Maluku');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Asahan, Sumatera Utara','Kab. Asahan, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Asmat, Papua','Kab. Asmat, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Badung, Bali','Kab. Badung, Bali');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Balangan, Kalimantan Selatan','Kab. Balangan, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Balikpapan, Kalimantan Timur','Kota Balikpapan, Kalimantan Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Banda Aceh, Aceh','Kota Banda Aceh, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Bandar Lampung, Lampung','Kota Bandar Lampung, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Bandung, Jawa Barat','Kota Bandung, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bandung, Jawa Barat','Kab. Bandung, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bandung Barat, Jawa Barat','Kab. Bandung Barat, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Banggai, Sulawesi Tengah','Kab. Banggai, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Banggai Kepulauan, Sulawesi Tengah','Kab. Banggai Kepulauan, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Banggai Laut, Sulawesi Tengah','Kab. Banggai Laut, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bangka, Kepulauan Bangka Belitung','Kab. Bangka, Kepulauan Bangka Belitung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bangka Barat, Kepulauan Bangka Belitung','Kab. Bangka Barat, Kepulauan Bangka Belitung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bangka Selatan, Kepulauan Bangka Belitung','Kab. Bangka Selatan, Kepulauan Bangka Belitung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bangka Tengah, Kepulauan Bangka Belitung','Kab. Bangka Tengah, Kepulauan Bangka Belitung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bangkalan, Jawa Timur','Kab. Bangkalan, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bangli, Bali','Kab. Bangli, Bali');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Banjar, Jawa Barat','Kota Banjar, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Banjar, Kalimantan Selatan','Kab. Banjar, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Banjarbaru, Kalimantan Selatan','Kota Banjarbaru, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Banjarmasin, Kalimantan Selatan','Kota Banjarmasin, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Banjarnegara, Jawa Tengah','Kab. Banjarnegara, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bantaeng, Sulawesi Selatan','Kab. Bantaeng, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bantul, DI Yogyakarta','Kab. Bantul, DI Yogyakarta');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Banyuasin, Sumatera Selatan','Kab. Banyuasin, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Banyumas, Jawa Tengah','Kab. Banyumas, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Banyuwangi, Jawa Timur','Kab. Banyuwangi, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Barito Kuala, Kalimantan Selatan','Kab. Barito Kuala, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Barito Selatan, Kalimantan Tengah','Kab. Barito Selatan, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Barito Timur, Kalimantan Tengah','Kab. Barito Timur, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Barito Utara, Kalimantan Tengah','Kab. Barito Utara, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Barru, Sulawesi Selatan','Kab. Barru, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Batam, Kepulauan Riau','Kota Batam, Kepulauan Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Batang, Jawa Tengah','Kab. Batang, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Batang Hari, Jambi','Kab. Batang Hari, Jambi');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Batu, Jawa Timur','Kota Batu, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Batu Bara, Sumatera Utara','Kab. Batu Bara, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Bau-Bau, Sulawesi Tenggara','Kota Bau-Bau, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Bekasi, Jawa Barat','Kota Bekasi, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bekasi, Jawa Barat','Kab. Bekasi, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Belitung, Kepulauan Bangka Belitung','Kab. Belitung, Kepulauan Bangka Belitung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Belitung Timur, Kepulauan Bangka Belitung','Kab. Belitung Timur, Kepulauan Bangka Belitung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Belu, Nusa Tenggara Timur','Kab. Belu, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bener Meriah, Aceh','Kab. Bener Meriah, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bengkalis, Riau','Kab. Bengkalis, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bengkayang, Kalimantan Barat','Kab. Bengkayang, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Bengkulu, Bengkulu','Kota Bengkulu, Bengkulu');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bengkulu Selatan, Bengkulu','Kab. Bengkulu Selatan, Bengkulu');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bengkulu Tengah, Bengkulu','Kab. Bengkulu Tengah, Bengkulu');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bengkulu Utara, Bengkulu','Kab. Bengkulu Utara, Bengkulu');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Berau, Kalimantan Timur','Kab. Berau, Kalimantan Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Biak Numfor, Papua','Kab. Biak Numfor, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bima, Nusa Tenggara Barat','Kab. Bima, Nusa Tenggara Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Bima, Nusa Tenggara Barat','Kota Bima, Nusa Tenggara Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Binjai, Sumatera Utara','Kota Binjai, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bintan, Kepulauan Riau','Kab. Bintan, Kepulauan Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bireuen, Aceh','Kab. Bireuen, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Bitung, Sulawesi Utara','Kota Bitung, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Blitar, Jawa Timur','Kab. Blitar, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Blitar, Jawa Timur','Kota Blitar, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Blora, Jawa Tengah','Kab. Blora, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Boalemo, Gorontalo','Kab. Boalemo, Gorontalo');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bogor, Jawa Barat','Kab. Bogor, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Bogor, Jawa Barat','Kota Bogor, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bojonegoro, Jawa Timur','Kab. Bojonegoro, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bolaang Mongondow, Sulawesi Utara','Kab. Bolaang Mongondow, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bolaang Mongondow Selatan, Sulawesi Utara','Kab. Bolaang Mongondow Selatan, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bolaang Mongondow Timur, Sulawesi Utara','Kab. Bolaang Mongondow Timur, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bolaang Mongondow Utara, Sulawesi Utara','Kab. Bolaang Mongondow Utara, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bombana, Sulawesi Tenggara','Kab. Bombana, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bondowoso, Jawa Timur','Kab. Bondowoso, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bone, Sulawesi Selatan','Kab. Bone, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bone Bolango, Gorontalo','Kab. Bone Bolango, Gorontalo');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Bontang, Kalimantan Timur','Kota Bontang, Kalimantan Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Boven Digoel, Papua','Kab. Boven Digoel, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Boyolali, Jawa Tengah','Kab. Boyolali, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Brebes, Jawa Tengah','Kab. Brebes, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Bukittinggi, Sumatera Barat','Kota Bukittinggi, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Buleleng, Bali','Kab. Buleleng, Bali');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bulukumba, Sulawesi Selatan','Kab. Bulukumba, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bulungan, Kalimantan Utara','Kab. Bulungan, Kalimantan Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Bungo, Jambi','Kab. Bungo, Jambi');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Buol, Sulawesi Tengah','Kab. Buol, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Buru, Maluku','Kab. Buru, Maluku');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Buru Selatan, Maluku','Kab. Buru Selatan, Maluku');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Buton, Sulawesi Tenggara','Kab. Buton, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Buton Selatan, Sulawesi Tenggara','Kab. Buton Selatan, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Buton Tengah, Sulawesi Tenggara','Kab. Buton Tengah, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Buton Utara, Sulawesi Tenggara','Kab. Buton Utara, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Ciamis, Jawa Barat','Kab. Ciamis, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Cianjur, Jawa Barat','Kab. Cianjur, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Cilacap, Jawa Tengah','Kab. Cilacap, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Cilegon, Banten','Kota Cilegon, Banten');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Cimahi, Jawa Barat','Kota Cimahi, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Cirebon, Jawa Barat','Kota Cirebon, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Cirebon, Jawa Barat','Kab. Cirebon, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Dairi, Sumatera Utara','Kab. Dairi, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Deiyai, Papua','Kab. Deiyai, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Deli Serdang, Sumatera Utara','Kab. Deli Serdang, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Demak, Jawa Tengah','Kab. Demak, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Denpasar, Bali','Kota Denpasar, Bali');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Depok, Jawa Barat','Kota Depok, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Dharmasraya, Sumatera Barat','Kab. Dharmasraya, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Dogiyai, Papua','Kab. Dogiyai, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Dompu, Nusa Tenggara Barat','Kab. Dompu, Nusa Tenggara Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Donggala, Sulawesi Tengah','Kab. Donggala, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Dumai, Riau','Kota Dumai, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Empat Lawang, Sumatera Selatan','Kab. Empat Lawang, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Ende, Nusa Tenggara Timur','Kab. Ende, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Enrekang, Sulawesi Selatan','Kab. Enrekang, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Fakfak, Papua Barat','Kab. Fakfak, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Flores Timur, Nusa Tenggara Timur','Kab. Flores Timur, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Garut, Jawa Barat','Kab. Garut, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Gayo Lues, Aceh','Kab. Gayo Lues, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Gianyar, Bali','Kab. Gianyar, Bali');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Gorontalo, Gorontalo','Kab. Gorontalo, Gorontalo');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Gorontalo, Gorontalo','Kota Gorontalo, Gorontalo');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Gorontalo Utara, Gorontalo','Kab. Gorontalo Utara, Gorontalo');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Gowa, Sulawesi Selatan','Kab. Gowa, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Gresik, Jawa Timur','Kab. Gresik, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Grobogan, Jawa Tengah','Kab. Grobogan, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Gunung Kidul, DI Yogyakarta','Kab. Gunung Kidul, DI Yogyakarta');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Gunung Mas, Kalimantan Tengah','Kab. Gunung Mas, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Gunungsitoli, Sumatera Utara','Kota Gunungsitoli, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Halmahera Barat, Maluku Utara','Kab. Halmahera Barat, Maluku Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Halmahera Selatan, Maluku Utara','Kab. Halmahera Selatan, Maluku Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Halmahera Tengah, Maluku Utara','Kab. Halmahera Tengah, Maluku Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Halmahera Timur, Maluku Utara','Kab. Halmahera Timur, Maluku Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Halmahera Utara, Maluku Utara','Kab. Halmahera Utara, Maluku Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Hulu Sungai Selatan, Kalimantan Selatan','Kab. Hulu Sungai Selatan, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Hulu Sungai Tengah, Kalimantan Selatan','Kab. Hulu Sungai Tengah, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Hulu Sungai Utara, Kalimantan Selatan','Kab. Hulu Sungai Utara, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Humbang Hasundutan, Sumatera Utara','Kab. Humbang Hasundutan, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Indragiri Hilir, Riau','Kab. Indragiri Hilir, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Indragiri Hulu, Riau','Kab. Indragiri Hulu, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Indramayu, Jawa Barat','Kab. Indramayu, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Intan Jaya, Papua','Kab. Intan Jaya, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Jakarta Barat, DKI Jakarta','Kota Jakarta Barat, DKI Jakarta');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Jakarta Pusat, DKI Jakarta','Kota Jakarta Pusat, DKI Jakarta');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Jakarta Selatan, DKI Jakarta','Kota Jakarta Selatan, DKI Jakarta');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Jakarta Timur, DKI Jakarta','Kota Jakarta Timur, DKI Jakarta');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Jakarta Utara, DKI Jakarta','Kota Jakarta Utara, DKI Jakarta');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Jambi, Jambi','Kota Jambi, Jambi');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Jayapura, Papua','Kab. Jayapura, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Jayapura, Papua','Kota Jayapura, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Jayawijaya, Papua','Kab. Jayawijaya, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Jember, Jawa Timur','Kab. Jember, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Jembrana, Bali','Kab. Jembrana, Bali');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Jeneponto, Sulawesi Selatan','Kab. Jeneponto, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Jepara, Jawa Tengah','Kab. Jepara, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Jombang, Jawa Timur','Kab. Jombang, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kaimana, Papua Barat','Kab. Kaimana, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kampar, Riau','Kab. Kampar, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kapuas, Kalimantan Tengah','Kab. Kapuas, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kapuas Hulu, Kalimantan Barat','Kab. Kapuas Hulu, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Karanganyar, Jawa Tengah','Kab. Karanganyar, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Karangasem, Bali','Kab. Karangasem, Bali');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Karawang, Jawa Barat','Kab. Karawang, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Karimun, Kepulauan Riau','Kab. Karimun, Kepulauan Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Karo, Sumatera Utara','Kab. Karo, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Katingan, Kalimantan Tengah','Kab. Katingan, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kaur, Bengkulu','Kab. Kaur, Bengkulu');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kayong Utara, Kalimantan Barat','Kab. Kayong Utara, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kebumen, Jawa Tengah','Kab. Kebumen, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kediri, Jawa Timur','Kab. Kediri, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Kediri, Jawa Timur','Kota Kediri, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Keerom, Papua','Kab. Keerom, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kendal, Jawa Tengah','Kab. Kendal, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Kendari, Sulawesi Tenggara','Kota Kendari, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepahiang, Bengkulu','Kab. Kepahiang, Bengkulu');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepulauan Anambas, Kepulauan Riau','Kab. Kepulauan Anambas, Kepulauan Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepulauan Aru, Maluku','Kab. Kepulauan Aru, Maluku');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepulauan Mentawai, Sumatera Barat','Kab. Kepulauan Mentawai, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepulauan Meranti, Riau','Kab. Kepulauan Meranti, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepulauan Sangihe, Sulawesi Utara','Kab. Kepulauan Sangihe, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepulauan Selayar, Sulawesi Selatan','Kab. Kepulauan Selayar, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepulauan Seribu, DKI Jakarta','Kab. Kepulauan Seribu, DKI Jakarta');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepulauan Siau Tagulandang Biaro (Sitaro), Sulawesi Utara','Kab. Kepulauan Siau Tagulandang Biaro (Sitaro), Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepulauan Sula, Maluku Utara','Kab. Kepulauan Sula, Maluku Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepulauan Talaud, Sulawesi Utara','Kab. Kepulauan Talaud, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kepulauan Yapen, Papua','Kab. Kepulauan Yapen, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kerinci, Jambi','Kab. Kerinci, Jambi');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Ketapang, Kalimantan Barat','Kab. Ketapang, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Klaten, Jawa Tengah','Kab. Klaten, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Klungkung, Bali','Kab. Klungkung, Bali');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kolaka, Sulawesi Tenggara','Kab. Kolaka, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kolaka Timur, Sulawesi Tenggara','Kab. Kolaka Timur, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kolaka Utara, Sulawesi Tenggara','Kab. Kolaka Utara, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Konawe, Sulawesi Tenggara','Kab. Konawe, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Konawe Kepulauan, Sulawesi Tenggara','Kab. Konawe Kepulauan, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Konawe Selatan, Sulawesi Tenggara','Kab. Konawe Selatan, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Konawe Utara, Sulawesi Tenggara','Kab. Konawe Utara, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kotabaru, Kalimantan Selatan','Kab. Kotabaru, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Kotamobagu, Sulawesi Utara','Kota Kotamobagu, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kotawaringin Barat, Kalimantan Tengah','Kab. Kotawaringin Barat, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kotawaringin Timur, Kalimantan Tengah','Kab. Kotawaringin Timur, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kuantan Singingi, Riau','Kab. Kuantan Singingi, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kubu Raya, Kalimantan Barat','Kab. Kubu Raya, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kudus, Jawa Tengah','Kab. Kudus, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kulon Progo, DI Yogyakarta','Kab. Kulon Progo, DI Yogyakarta');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kuningan, Jawa Barat','Kab. Kuningan, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kupang, Nusa Tenggara Timur','Kab. Kupang, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Kupang, Nusa Tenggara Timur','Kota Kupang, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kutai Barat, Kalimantan Timur','Kab. Kutai Barat, Kalimantan Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kutai Kartanegara, Kalimantan Timur','Kab. Kutai Kartanegara, Kalimantan Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Kutai Timur, Kalimantan Timur','Kab. Kutai Timur, Kalimantan Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Labuhanbatu, Sumatera Utara','Kab. Labuhanbatu, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Labuhanbatu Selatan, Sumatera Utara','Kab. Labuhanbatu Selatan, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Labuhanbatu Utara, Sumatera Utara','Kab. Labuhanbatu Utara, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lahat, Sumatera Selatan','Kab. Lahat, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lamandau, Kalimantan Tengah','Kab. Lamandau, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lamongan, Jawa Timur','Kab. Lamongan, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lampung Barat, Lampung','Kab. Lampung Barat, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lampung Selatan, Lampung','Kab. Lampung Selatan, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lampung Tengah, Lampung','Kab. Lampung Tengah, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lampung Timur, Lampung','Kab. Lampung Timur, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lampung Utara, Lampung','Kab. Lampung Utara, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Landak, Kalimantan Barat','Kab. Landak, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Langkat, Sumatera Utara','Kab. Langkat, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Langsa, Aceh','Kota Langsa, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lanny Jaya, Papua','Kab. Lanny Jaya, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lebak, Banten','Kab. Lebak, Banten');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lebong, Bengkulu','Kab. Lebong, Bengkulu');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lembata, Nusa Tenggara Timur','Kab. Lembata, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Lhokseumawe, Aceh','Kota Lhokseumawe, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lima Puluh Kota, Sumatera Barat','Kab. Lima Puluh Kota, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lingga, Kepulauan Riau','Kab. Lingga, Kepulauan Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lombok Barat, Nusa Tenggara Barat','Kab. Lombok Barat, Nusa Tenggara Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lombok Tengah, Nusa Tenggara Barat','Kab. Lombok Tengah, Nusa Tenggara Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lombok Timur, Nusa Tenggara Barat','Kab. Lombok Timur, Nusa Tenggara Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lombok Utara, Nusa Tenggara Barat','Kab. Lombok Utara, Nusa Tenggara Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Lubuk Linggau, Sumatera Selatan','Kota Lubuk Linggau, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Lumajang, Jawa Timur','Kab. Lumajang, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Luwu, Sulawesi Selatan','Kab. Luwu, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Luwu Timur, Sulawesi Selatan','Kab. Luwu Timur, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Luwu Utara, Sulawesi Selatan','Kab. Luwu Utara, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Madiun, Jawa Timur','Kab. Madiun, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Madiun, Jawa Timur','Kota Madiun, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Magelang, Jawa Tengah','Kab. Magelang, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Magelang, Jawa Tengah','Kota Magelang, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Magetan, Jawa Timur','Kab. Magetan, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mahakam Ulu, Kalimantan Timur','Kab. Mahakam Ulu, Kalimantan Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Majalengka, Jawa Barat','Kab. Majalengka, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Majene, Sulawesi Barat','Kab. Majene, Sulawesi Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Makassar, Sulawesi Selatan','Kota Makassar, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Malaka, Nusa Tenggara Timur','Kab. Malaka, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Malang, Jawa Timur','Kab. Malang, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Malang, Jawa Timur','Kota Malang, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Malinau, Kalimantan Utara','Kab. Malinau, Kalimantan Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Maluku Barat Daya, Maluku','Kab. Maluku Barat Daya, Maluku');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Maluku Tengah, Maluku','Kab. Maluku Tengah, Maluku');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Maluku Tenggara, Maluku','Kab. Maluku Tenggara, Maluku');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Maluku Tenggara Barat, Maluku','Kab. Maluku Tenggara Barat, Maluku');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mamasa, Sulawesi Barat','Kab. Mamasa, Sulawesi Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mamberamo Raya, Papua','Kab. Mamberamo Raya, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mamberamo Tengah, Papua','Kab. Mamberamo Tengah, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mamuju, Sulawesi Barat','Kab. Mamuju, Sulawesi Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mamuju Tengah, Sulawesi Barat','Kab. Mamuju Tengah, Sulawesi Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mamuju Utara, Sulawesi Barat','Kab. Mamuju Utara, Sulawesi Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Manado, Sulawesi Utara','Kota Manado, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mandailing Natal, Sumatera Utara','Kab. Mandailing Natal, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Manggarai, Nusa Tenggara Timur','Kab. Manggarai, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Manggarai Barat, Nusa Tenggara Timur','Kab. Manggarai Barat, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Manggarai Timur, Nusa Tenggara Timur','Kab. Manggarai Timur, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Manokwari, Papua Barat','Kab. Manokwari, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Manokwari Selatan, Papua Barat','Kab. Manokwari Selatan, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mappi, Papua','Kab. Mappi, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Maros, Sulawesi Selatan','Kab. Maros, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Mataram, Nusa Tenggara Barat','Kota Mataram, Nusa Tenggara Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Maybrat, Papua Barat','Kab. Maybrat, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Medan, Sumatera Utara','Kota Medan, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Melawi, Kalimantan Barat','Kab. Melawi, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mempawah, Kalimantan Barat','Kab. Mempawah, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Merangin, Jambi','Kab. Merangin, Jambi');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Merauke, Papua','Kab. Merauke, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mesuji, Lampung','Kab. Mesuji, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Metro, Lampung','Kota Metro, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mimika, Papua','Kab. Mimika, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Minahasa, Sulawesi Utara','Kab. Minahasa, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Minahasa Selatan, Sulawesi Utara','Kab. Minahasa Selatan, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Minahasa Tenggara, Sulawesi Utara','Kab. Minahasa Tenggara, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Minahasa Utara, Sulawesi Utara','Kab. Minahasa Utara, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Mojokerto, Jawa Timur','Kab. Mojokerto, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Mojokerto, Jawa Timur','Kota Mojokerto, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Morowali, Sulawesi Tengah','Kab. Morowali, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Morowali Utara, Sulawesi Tengah','Kab. Morowali Utara, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Muara Enim, Sumatera Selatan','Kab. Muara Enim, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Muaro Jambi, Jambi','Kab. Muaro Jambi, Jambi');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Muko Muko, Bengkulu','Kab. Muko Muko, Bengkulu');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Muna, Sulawesi Tenggara','Kab. Muna, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Muna Barat, Sulawesi Tenggara','Kab. Muna Barat, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Murung Raya, Kalimantan Tengah','Kab. Murung Raya, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Musi Banyuasin, Sumatera Selatan','Kab. Musi Banyuasin, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Musi Rawas, Sumatera Selatan','Kab. Musi Rawas, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Musi Rawas Utara, Sumatera Selatan','Kab. Musi Rawas Utara, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Nabire, Papua','Kab. Nabire, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Nagan Raya, Aceh','Kab. Nagan Raya, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Nagekeo, Nusa Tenggara Timur','Kab. Nagekeo, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Natuna, Kepulauan Riau','Kab. Natuna, Kepulauan Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Nduga, Papua','Kab. Nduga, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Ngada, Nusa Tenggara Timur','Kab. Ngada, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Nganjuk, Jawa Timur','Kab. Nganjuk, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Ngawi, Jawa Timur','Kab. Ngawi, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Nias, Sumatera Utara','Kab. Nias, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Nias Barat, Sumatera Utara','Kab. Nias Barat, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Nias Selatan, Sumatera Utara','Kab. Nias Selatan, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Nias Utara, Sumatera Utara','Kab. Nias Utara, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Nunukan, Kalimantan Utara','Kab. Nunukan, Kalimantan Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Ogan Ilir, Sumatera Selatan','Kab. Ogan Ilir, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Ogan Komering Ilir, Sumatera Selatan','Kab. Ogan Komering Ilir, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Ogan Komering Ulu, Sumatera Selatan','Kab. Ogan Komering Ulu, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Ogan Komering Ulu Selatan, Sumatera Selatan','Kab. Ogan Komering Ulu Selatan, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Ogan Komering Ulu Timur, Sumatera Selatan','Kab. Ogan Komering Ulu Timur, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pacitan, Jawa Timur','Kab. Pacitan, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Padang, Sumatera Barat','Kota Padang, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Padang Lawas, Sumatera Utara','Kab. Padang Lawas, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Padang Lawas Utara, Sumatera Utara','Kab. Padang Lawas Utara, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Padang Panjang, Sumatera Barat','Kota Padang Panjang, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Padang Pariaman, Sumatera Barat','Kab. Padang Pariaman, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Padang Sidempuan, Sumatera Utara','Kota Padang Sidempuan, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Pagar Alam, Sumatera Selatan','Kota Pagar Alam, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pakpak Bharat, Sumatera Utara','Kab. Pakpak Bharat, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Palangka Raya, Kalimantan Tengah','Kota Palangka Raya, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Palembang, Sumatera Selatan','Kota Palembang, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Palopo, Sulawesi Selatan','Kota Palopo, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Palu, Sulawesi Tengah','Kota Palu, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pamekasan, Jawa Timur','Kab. Pamekasan, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pandeglang, Banten','Kab. Pandeglang, Banten');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pangandaran, Jawa Barat','Kab. Pangandaran, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pangkajene Kepulauan, Sulawesi Selatan','Kab. Pangkajene Kepulauan, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Pangkal Pinang, Kepulauan Bangka Belitung','Kota Pangkal Pinang, Kepulauan Bangka Belitung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Paniai, Papua','Kab. Paniai, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Parepare, Sulawesi Selatan','Kota Parepare, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Pariaman, Sumatera Barat','Kota Pariaman, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Parigi Moutong, Sulawesi Tengah','Kab. Parigi Moutong, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pasaman, Sumatera Barat','Kab. Pasaman, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pasaman Barat, Sumatera Barat','Kab. Pasaman Barat, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Paser, Kalimantan Timur','Kab. Paser, Kalimantan Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pasuruan, Jawa Timur','Kab. Pasuruan, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Pasuruan, Jawa Timur','Kota Pasuruan, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pati, Jawa Tengah','Kab. Pati, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Payakumbuh, Sumatera Barat','Kota Payakumbuh, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pegunungan Arfak, Papua Barat','Kab. Pegunungan Arfak, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pegunungan Bintang, Papua','Kab. Pegunungan Bintang, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pekalongan, Jawa Tengah','Kab. Pekalongan, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Pekalongan, Jawa Tengah','Kota Pekalongan, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Pekanbaru, Riau','Kota Pekanbaru, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pelalawan, Riau','Kab. Pelalawan, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pemalang, Jawa Tengah','Kab. Pemalang, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Pematang Siantar, Sumatera Utara','Kota Pematang Siantar, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Penajam Paser Utara, Kalimantan Timur','Kab. Penajam Paser Utara, Kalimantan Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Penukal Abab Lematang Ilir, Sumatera Selatan','Kab. Penukal Abab Lematang Ilir, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pesawaran, Lampung','Kab. Pesawaran, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pesisir Barat, Lampung','Kab. Pesisir Barat, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pesisir Selatan, Sumatera Barat','Kab. Pesisir Selatan, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pidie, Aceh','Kab. Pidie, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pidie Jaya, Aceh','Kab. Pidie Jaya, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pinrang, Sulawesi Selatan','Kab. Pinrang, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pohuwato, Gorontalo','Kab. Pohuwato, Gorontalo');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Polewali Mandar, Sulawesi Barat','Kab. Polewali Mandar, Sulawesi Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Ponorogo, Jawa Timur','Kab. Ponorogo, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Pontianak, Kalimantan Barat','Kota Pontianak, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Poso, Sulawesi Tengah','Kab. Poso, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Prabumulih, Sumatera Selatan','Kota Prabumulih, Sumatera Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pringsewu, Lampung','Kab. Pringsewu, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Probolinggo, Jawa Timur','Kab. Probolinggo, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Probolinggo, Jawa Timur','Kota Probolinggo, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pulang Pisau, Kalimantan Tengah','Kab. Pulang Pisau, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pulau Morotai, Maluku Utara','Kab. Pulau Morotai, Maluku Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Pulau Taliabu, Maluku Utara','Kab. Pulau Taliabu, Maluku Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Puncak, Papua','Kab. Puncak, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Puncak Jaya, Papua','Kab. Puncak Jaya, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Purbalingga, Jawa Tengah','Kab. Purbalingga, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Purwakarta, Jawa Barat','Kab. Purwakarta, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Purworejo, Jawa Tengah','Kab. Purworejo, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Raja Ampat, Papua Barat','Kab. Raja Ampat, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Rejang Lebong, Bengkulu','Kab. Rejang Lebong, Bengkulu');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Rembang, Jawa Tengah','Kab. Rembang, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Rokan Hilir, Riau','Kab. Rokan Hilir, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Rokan Hulu, Riau','Kab. Rokan Hulu, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Rote Ndao, Nusa Tenggara Timur','Kab. Rote Ndao, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Sabang, Aceh','Kota Sabang, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sabu Raijua, Nusa Tenggara Timur','Kab. Sabu Raijua, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Salatiga, Jawa Tengah','Kota Salatiga, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Samarinda, Kalimantan Timur','Kota Samarinda, Kalimantan Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sambas, Kalimantan Barat','Kab. Sambas, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Samosir, Sumatera Utara','Kab. Samosir, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sampang, Jawa Timur','Kab. Sampang, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sanggau, Kalimantan Barat','Kab. Sanggau, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sarmi, Papua','Kab. Sarmi, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sarolangun, Jambi','Kab. Sarolangun, Jambi');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Sawah Lunto, Sumatera Barat','Kota Sawah Lunto, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sekadau, Kalimantan Barat','Kab. Sekadau, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Seluma, Bengkulu','Kab. Seluma, Bengkulu');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Semarang, Jawa Tengah','Kab. Semarang, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Semarang, Jawa Tengah','Kota Semarang, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Seram Bagian Barat, Maluku','Kab. Seram Bagian Barat, Maluku');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Seram Bagian Timur, Maluku','Kab. Seram Bagian Timur, Maluku');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Serang, Banten','Kota Serang, Banten');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Serang, Banten','Kab. Serang, Banten');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Serdang Bedagai, Sumatera Utara','Kab. Serdang Bedagai, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Seruyan, Kalimantan Tengah','Kab. Seruyan, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Siak, Riau','Kab. Siak, Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Sibolga, Sumatera Utara','Kota Sibolga, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sidenreng Rappang, Sulawesi Selatan','Kab. Sidenreng Rappang, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sidoarjo, Jawa Timur','Kab. Sidoarjo, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sigi, Sulawesi Tengah','Kab. Sigi, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sijunjung, Sumatera Barat','Kab. Sijunjung, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sikka, Nusa Tenggara Timur','Kab. Sikka, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Simalungun, Sumatera Utara','Kab. Simalungun, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Simeulue, Aceh','Kab. Simeulue, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Singkawang, Kalimantan Barat','Kota Singkawang, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sinjai, Sulawesi Selatan','Kab. Sinjai, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sintang, Kalimantan Barat','Kab. Sintang, Kalimantan Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Situbondo, Jawa Timur','Kab. Situbondo, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sleman, DI Yogyakarta','Kab. Sleman, DI Yogyakarta');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Solok, Sumatera Barat','Kab. Solok, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Solok, Sumatera Barat','Kota Solok, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Solok Selatan, Sumatera Barat','Kab. Solok Selatan, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Soppeng, Sulawesi Selatan','Kab. Soppeng, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sorong, Papua Barat','Kab. Sorong, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Sorong, Papua Barat','Kota Sorong, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sorong Selatan, Papua Barat','Kab. Sorong Selatan, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sragen, Jawa Tengah','Kab. Sragen, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Subang, Jawa Barat','Kab. Subang, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Subulussalam, Aceh','Kota Subulussalam, Aceh');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Sukabumi, Jawa Barat','Kota Sukabumi, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sukabumi, Jawa Barat','Kab. Sukabumi, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sukamara, Kalimantan Tengah','Kab. Sukamara, Kalimantan Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sukoharjo, Jawa Tengah','Kab. Sukoharjo, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sumba Barat, Nusa Tenggara Timur','Kab. Sumba Barat, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sumba Barat Daya, Nusa Tenggara Timur','Kab. Sumba Barat Daya, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sumba Tengah, Nusa Tenggara Timur','Kab. Sumba Tengah, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sumba Timur, Nusa Tenggara Timur','Kab. Sumba Timur, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sumbawa, Nusa Tenggara Barat','Kab. Sumbawa, Nusa Tenggara Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sumbawa Barat, Nusa Tenggara Barat','Kab. Sumbawa Barat, Nusa Tenggara Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sumedang, Jawa Barat','Kab. Sumedang, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Sumenep, Jawa Timur','Kab. Sumenep, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Sungaipenuh, Jambi','Kota Sungaipenuh, Jambi');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Supiori, Papua','Kab. Supiori, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Surabaya, Jawa Timur','Kota Surabaya, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Surakarta, Jawa Tengah','Kota Surakarta, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tabalong, Kalimantan Selatan','Kab. Tabalong, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tabanan, Bali','Kab. Tabanan, Bali');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Takalar, Sulawesi Selatan','Kab. Takalar, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tambrauw, Papua Barat','Kab. Tambrauw, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tana Tidung, Kalimantan Utara','Kab. Tana Tidung, Kalimantan Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tana Toraja, Sulawesi Selatan','Kab. Tana Toraja, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tanah Bumbu, Kalimantan Selatan','Kab. Tanah Bumbu, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tanah Datar, Sumatera Barat','Kab. Tanah Datar, Sumatera Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tanah Laut, Kalimantan Selatan','Kab. Tanah Laut, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Tangerang, Banten','Kota Tangerang, Banten');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tangerang, Banten','Kab. Tangerang, Banten');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Tangerang Selatan, Banten','Kota Tangerang Selatan, Banten');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tanggamus, Lampung','Kab. Tanggamus, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Tanjung Balai, Sumatera Utara','Kota Tanjung Balai, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tanjung Jabung Barat, Jambi','Kab. Tanjung Jabung Barat, Jambi');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tanjung Jabung Timur, Jambi','Kab. Tanjung Jabung Timur, Jambi');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Tanjung Pinang, Kepulauan Riau','Kota Tanjung Pinang, Kepulauan Riau');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tapanuli Selatan, Sumatera Utara','Kab. Tapanuli Selatan, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tapanuli Tengah, Sumatera Utara','Kab. Tapanuli Tengah, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tapanuli Utara, Sumatera Utara','Kab. Tapanuli Utara, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tapin, Kalimantan Selatan','Kab. Tapin, Kalimantan Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Tarakan, Kalimantan Utara','Kota Tarakan, Kalimantan Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Tasikmalaya, Jawa Barat','Kota Tasikmalaya, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tasikmalaya, Jawa Barat','Kab. Tasikmalaya, Jawa Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Tebing Tinggi, Sumatera Utara','Kota Tebing Tinggi, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tebo, Jambi','Kab. Tebo, Jambi');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tegal, Jawa Tengah','Kab. Tegal, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Tegal, Jawa Tengah','Kota Tegal, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Teluk Bintuni, Papua Barat','Kab. Teluk Bintuni, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Teluk Wondama, Papua Barat','Kab. Teluk Wondama, Papua Barat');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Temanggung, Jawa Tengah','Kab. Temanggung, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Ternate, Maluku Utara','Kota Ternate, Maluku Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Tidore Kepulauan, Maluku Utara','Kota Tidore Kepulauan, Maluku Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Timor Tengah Selatan, Nusa Tenggara Timur','Kab. Timor Tengah Selatan, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Timor Tengah Utara, Nusa Tenggara Timur','Kab. Timor Tengah Utara, Nusa Tenggara Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Toba Samosir, Sumatera Utara','Kab. Toba Samosir, Sumatera Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tojo Una-Una, Sulawesi Tengah','Kab. Tojo Una-Una, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Toli-Toli, Sulawesi Tengah','Kab. Toli-Toli, Sulawesi Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tolikara, Papua','Kab. Tolikara, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Tomohon, Sulawesi Utara','Kota Tomohon, Sulawesi Utara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Toraja Utara, Sulawesi Selatan','Kab. Toraja Utara, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Trenggalek, Jawa Timur','Kab. Trenggalek, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Tual, Maluku','Kota Tual, Maluku');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tuban, Jawa Timur','Kab. Tuban, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tulang Bawang, Lampung','Kab. Tulang Bawang, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tulang Bawang Barat, Lampung','Kab. Tulang Bawang Barat, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Tulungagung, Jawa Timur','Kab. Tulungagung, Jawa Timur');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Wajo, Sulawesi Selatan','Kab. Wajo, Sulawesi Selatan');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Wakatobi, Sulawesi Tenggara','Kab. Wakatobi, Sulawesi Tenggara');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Waropen, Papua','Kab. Waropen, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Way Kanan, Lampung','Kab. Way Kanan, Lampung');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Wonogiri, Jawa Tengah','Kab. Wonogiri, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Wonosobo, Jawa Tengah','Kab. Wonosobo, Jawa Tengah');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Yahukimo, Papua','Kab. Yahukimo, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kab. Yalimo, Papua','Kab. Yalimo, Papua');
INSERT INTO public.lookup(lookup_key, lookup_value, lookup_display_name) VALUES  ('city', 'Kota Yogyakarta, DI Yogyakarta','Kota Yogyakarta, DI Yogyakarta');